### ISSUE TITLE
Who made this?

### ISSUE THREAD

**Issue by ercfre** [MetaMask/logo#16]
Who made this?

Please contact me. I'd like to hire someone to re-create the same effect for a different logo.

Apologies if this is an inappropriate use of the issues section.

Thank you.

**Comment by mcmire** [comment]
Sorry about the late reply. I hope you were able to get the assistance you needed for your project. You are free to reach out to @danfinlay and @kumavis, but in the future you may have better luck in using some sort of hiring service like Upwork or Fiverr. I'm going to close this since we'd prefer to use issues for bugs and technical questions, but let me know if you have any more questions.
